# Generated by Django 3.2.25 on 2024-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likerty', '0002_alter_survey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
