# Generated by Django 3.2.25 on 2024-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likerty', '0003_auto_20240422_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
