# Generated by Django 3.2.25 on 2024-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likerty', '0005_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
