# Generated by Django 3.2.25 on 2024-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likerty', '0006_response_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='slug',
        ),
        migrations.AlterField(
            model_name='survey',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
