# Generated by Django 3.2.25 on 2024-05-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likerty', '0007_auto_20240515_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='abuse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
