# Generated by Django 3.2.25 on 2024-10-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likerty', '0008_auto_20240517_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
