# Generated by Django 3.2.25 on 2024-04-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_location_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('allocation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.round')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.programme')),
            ],
        ),
    ]
