# Generated by Django 3.2.25 on 2024-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_round_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='slug',
            field=models.SlugField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
