# Generated by Django 3.2.25 on 2024-04-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_round_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='institute',
            new_name='institution',
        ),
        migrations.AddField(
            model_name='round',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.department'),
        ),
    ]
