# Generated by Django 3.2.25 on 2024-04-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20240410_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.institution'),
        ),
    ]
