# Generated by Django 3.2.25 on 2024-04-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20240410_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='admin_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_admin_dept', to='projects.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='admin_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.department'),
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admin_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upervisor_admin_dept', to='projects.department')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admin_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_admin_dept', to='projects.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.institution')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.UniqueConstraint(fields=('name', 'institution'), name='unique_prerequisite'),
        ),
    ]
