# Generated by Django 3.2.25 on 2024-04-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20240410_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supervisors',
            new_name='Supervisor',
        ),
    ]
