# Generated by Django 3.2.25 on 2024-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20240410_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='projects_PG',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='projects_UG',
            field=models.IntegerField(default=3),
        ),
    ]
