# Generated by Django 3.2.25 on 2024-04-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='admin_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_admin_dept', to='projects.department'),
        ),
        migrations.AddField(
            model_name='programme',
            name='admin_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_admin_dept', to='projects.department'),
        ),
    ]
