# Generated by Django 3.2.25 on 2024-04-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20240410_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('admin_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_set_admin_dept', to='projects.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.institution')),
                ('keywords', models.ManyToManyField(blank=True, related_name='supervisor_set_keywords', to='projects.ProjectKeyword')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.supervisor')),
                ('types', models.ManyToManyField(blank=True, related_name='supervisor_set_types', to='projects.ProjectType')),
            ],
        ),
    ]
