# Generated by Django 3.2.25 on 2024-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_supervisorset'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorset',
            name='available_for_pg',
            field=models.IntegerField(default=1, verbose_name='Available for PG'),
        ),
        migrations.AddField(
            model_name='supervisorset',
            name='available_for_ug',
            field=models.IntegerField(default=3, verbose_name='Available for UG'),
        ),
    ]
