# Generated by Django 3.2.25 on 2024-04-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20240412_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('allocation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.round', verbose_name='Round')),
                ('primary_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.supervisor')),
                ('second_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_supervisor', to='projects.supervisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.student')),
                ('supervisor_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.supervisorset')),
            ],
        ),
    ]
