# Generated by Django 3.2.25 on 2024-04-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20240412_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ug_or_pg',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2, verbose_name='UG/PG'),
        ),
        migrations.AlterField(
            model_name='project',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.institution'),
        ),
    ]
