# Generated by Django 3.2.25 on 2024-04-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20240412_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allocation_round',
        ),
        migrations.RemoveField(
            model_name='project',
            name='primary_supervisor',
        ),
    ]
