# Generated by Django 3.2.25 on 2024-04-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20240415_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institute_logos/'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='supervisor',
            constraint=models.UniqueConstraint(fields=('username', 'institution'), name='unique_supervisor'),
        ),
    ]
