# Generated by Django 3.2.25 on 2024-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20240415_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
