# Generated by Django 3.2.25 on 2024-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20240417_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorset',
            name='available_for_pg',
            field=models.PositiveIntegerField(default=1, verbose_name='Available for PG'),
        ),
        migrations.AlterField(
            model_name='supervisorset',
            name='available_for_ug',
            field=models.PositiveIntegerField(default=3, verbose_name='Available for UG'),
        ),
    ]
