# Generated by Django 3.2.25 on 2024-04-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20240417_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='primary_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_supervisor', to='projects.supervisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round', to='projects.round'),
        ),
        migrations.AddField(
            model_name='project',
            name='second_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_supervisor', to='projects.supervisor'),
        ),
    ]
