# Generated by Django 3.2.25 on 2024-04-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20240423_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='projects.student'),
        ),
    ]
