# Generated by Django 3.2.25 on 2024-04-24 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_project_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorset',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_set_prerequisites', to='projects.prerequisite'),
        ),
    ]
