# Generated by Django 3.2.25 on 2024-04-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_supervisorset_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.department'),
        ),
        migrations.AddField(
            model_name='programme',
            name='exclue_programme',
            field=models.ManyToManyField(blank=True, related_name='exclude_programme', to='projects.Programme'),
        ),
    ]
