# Generated by Django 3.2.25 on 2024-04-26 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20240426_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='department',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='exclue_programme',
        ),
        migrations.AddField(
            model_name='programme',
            name='ug_or_pg',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2, verbose_name='UG/PG'),
        ),
        migrations.AddField(
            model_name='projectkeyword',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.department'),
        ),
        migrations.AddField(
            model_name='projectkeyword',
            name='exclude_programmes',
            field=models.ManyToManyField(blank=True, related_name='exclude_programmes', to='projects.Programme'),
        ),
        migrations.AddField(
            model_name='projectkeyword',
            name='pg_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectkeyword',
            name='ug_only',
            field=models.BooleanField(default=False),
        ),
    ]
