# Generated by Django 3.2.25 on 2024-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20240426_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectkeyword',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
