# Generated by Django 3.2.25 on 2024-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_projectkeyword_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='number_of_keywords',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='round',
            name='number_of_types',
            field=models.IntegerField(default=3),
        ),
    ]
