# Generated by Django 3.2.25 on 2024-04-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20240429_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='project_keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='project_types',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
