# Generated by Django 3.2.25 on 2024-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20240429_1309'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('name', 'institution', 'admin_dept'), name='unique_round'),
        ),
    ]
