# Generated by Django 3.2.25 on 2024-04-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_round_unique_round'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='round',
            name='unique_round',
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('name', 'institution', 'department'), name='unique_round'),
        ),
    ]
