# Generated by Django 3.2.25 on 2024-04-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20240429_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='limit_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limit_to_department', to='projects.department'),
        ),
    ]
