# Generated by Django 3.2.25 on 2024-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_projecttype_limit_to_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
