# Generated by Django 3.2.25 on 2024-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_alter_supervisor_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supervisor',
            name='unique_supervisor',
        ),
        migrations.AddConstraint(
            model_name='supervisor',
            constraint=models.UniqueConstraint(fields=('username', 'admin_dept'), name='unique_supervisor'),
        ),
    ]
