# Generated by Django 3.2.25 on 2024-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20240430_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
