# Generated by Django 3.2.25 on 2024-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_alter_supervisor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mbiolsci',
            field=models.BooleanField(default=False),
        ),
    ]
