# Generated by Django 3.2.25 on 2024-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_student_mbiolsci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mbiolsci',
            field=models.BooleanField(default=False, help_text='Select your programme (or pathway if MBiolSci).', verbose_name='Programme/Pathway'),
        ),
    ]
