# Generated by Django 3.2.25 on 2024-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_alter_student_mbiolsci'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='help_video_iframe',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mbiolsci',
            field=models.BooleanField(default=False),
        ),
    ]
