# Generated by Django 3.2.25 on 2024-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20240510_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='priority',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
