# Generated by Django 3.2.25 on 2024-06-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_student_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mbiolsci',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
