# Generated by Django 3.2.25 on 2024-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_student_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, help_text='Please provide any additional information that you think may be relevant to your project allocation.', max_length=2000, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='supervisorset',
            name='available_for_pg',
            field=models.PositiveIntegerField(default=0, verbose_name='Available for PG'),
        ),
        migrations.AlterField(
            model_name='supervisorset',
            name='available_for_ug',
            field=models.PositiveIntegerField(default=0, verbose_name='Available for UG'),
        ),
    ]
