# Generated by Django 3.2.25 on 2024-07-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20240712_0845'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student_round',
        ),
    ]
