# Generated by Django 3.2.25 on 2024-09-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_remove_student_unique_student_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='supervisor_set',
        ),
    ]
