# Generated by Django 3.2.25 on 2024-09-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='file',
            new_name='output',
        ),
    ]
