# Generated by Django 3.2.25 on 2024-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20240913_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='prerequisites_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='priority_on',
            field=models.BooleanField(default=False),
        ),
    ]
