version: "3.9"

services:

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
      - redis
    container_name: app
  
  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - SECRET_KEY=${SECRET_KEY}    

  # Celery
  celery:
    restart: always
    build:
      context: .
    command: >
      sh -c "celery -A app worker -l INFO"
    volumes:
      - ./app:/app
    container_name: celery-secure
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
      - app



      
