# Generated by Django 3.2.24 on 2024-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('semester', models.CharField(max_length=28)),
                ('level', models.CharField(max_length=28)),
                ('credits', models.IntegerField()),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compulsory', models.BooleanField(default=False)),
                ('practical', models.BooleanField(default=False)),
                ('in_programmes', models.ManyToManyField(related_name='programmes', to='choices.Programme')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='_choices_module_prerequisites_+', to='choices.Module')),
                ('requisite_for', models.ManyToManyField(blank=True, related_name='_choices_module_requisite_for_+', to='choices.Module')),
            ],
        ),
    ]
