# Generated by Django 3.2.24 on 2024-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_alter_module_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='requisite_for',
        ),
        migrations.AlterField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='choices.Module'),
        ),
    ]
