# Generated by Django 3.2.24 on 2024-02-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_programme_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
