# Generated by Django 3.2.24 on 2024-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0005_module_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='short_title',
        ),
        migrations.AddField(
            model_name='programme',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
