# Generated by Django 3.2.24 on 2024-02-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20240222_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
