# Generated by Django 3.2.24 on 2024-02-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0007_alter_programme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
