# Generated by Django 3.2.24 on 2024-02-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0008_programme_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='html',
        ),
    ]
