# Generated by Django 3.2.24 on 2024-03-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0009_remove_module_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=1)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='choices.programme')),
            ],
        ),
    ]
