# Generated by Django 3.2.23 on 2024-02-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifesci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='preloaded_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='figure',
            field=models.FileField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AddField(
            model_name='question',
            name='figure_example',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
