# Generated by Django 3.2.24 on 2024-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifesci', '0002_auto_20240211_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example_answer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
