# Generated by Django 3.2.23 on 2024-01-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
