# Generated by Django 3.2.23 on 2024-01-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='function_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
