# Generated by Django 3.2.23 on 2024-01-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_question_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='submitted',
            field=models.IntegerField(default=0),
        ),
    ]
