# Generated by Django 3.2.23 on 2024-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_answer_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted',
            field=models.BigIntegerField(default=0),
        ),
    ]
