# Generated by Django 3.2.23 on 2024-01-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_alter_answer_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reddit',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='resources',
            field=models.URLField(blank=True, null=True),
        ),
    ]
