# Generated by Django 3.2.23 on 2024-01-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_auto_20240117_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
