# Generated by Django 3.2.23 on 2024-01-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foundation.question'),
        ),
    ]
