# Generated by Django 3.2.23 on 2024-01-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0009_resource_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='puzzle_input',
            field=models.BooleanField(default=True),
        ),
    ]
