# Generated by Django 3.2.25 on 2024-06-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
