# Generated by Django 3.2.25 on 2024-06-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_url', models.URLField()),
                ('video_timestamp', models.URLField()),
                ('transcript_text', models.TextField()),
                ('transcript_timestamp', models.CharField(blank=True, max_length=128, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captionsearch.video')),
            ],
        ),
    ]
