# Generated by Django 3.2.25 on 2024-06-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captionsearch', '0002_auto_20240610_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caption',
            name='video_timestamp',
        ),
    ]
