# Generated by Django 3.2.25 on 2024-07-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationprofile',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='presentationrequest',
            name='uuid',
        ),
    ]
