# Generated by Django 3.2.25 on 2024-07-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_presentationrequest_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationrequest',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
