# Generated by Django 3.2.25 on 2024-05-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='type',
            field=models.CharField(default='LO', max_length=100),
        ),
    ]
