# Generated by Django 3.2.25 on 2024-05-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_supervisor_max_projects'),
        ('ilo', '0002_learningobjective_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilo.learningobjective')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.supervisor')),
            ],
        ),
    ]
