# Generated by Django 3.2.25 on 2024-03-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
