# Generated by Django 3.2.25 on 2024-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20240314_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
