# Generated by Django 3.2.25 on 2024-03-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportrequest_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report/'),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.reportprofile'),
        ),
    ]
