# Generated by Django 3.2.25 on 2024-03-14 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20240314_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
