# Generated by Django 3.2.25 on 2024-03-14 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_reportprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reportprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
