# Generated by Django 3.2.25 on 2024-03-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20240314_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='assignment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='course_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
