# Generated by Django 3.2.25 on 2024-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20240314_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='max_downloads',
            field=models.IntegerField(default=3),
        ),
    ]
