# Generated by Django 3.2.25 on 2024-03-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_reportprofile_max_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
