# Generated by Django 3.2.25 on 2024-03-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_reportprofile_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportprofile',
            name='max_downloads',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='reportprofile',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
