# Generated by Django 3.2.23 on 2024-02-05 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foundation2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='human',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human', to=settings.AUTH_USER_MODEL),
        ),
    ]
