# Generated by Django 3.2.23 on 2024-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20231218_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='University of Liverpool', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
