# Generated by Django 3.2.23 on 2024-01-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20240112_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('are_you_human', models.BooleanField(default=False, verbose_name='Are you human?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.event')),
            ],
        ),
    ]
