# Generated by Django 3.2.23 on 2024-01-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='are_you_human',
        ),
        migrations.AddField(
            model_name='registration',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
