# Generated by Django 3.2.23 on 2024-01-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20240112_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.IntegerField(default=0),
        ),
    ]
