# Generated by Django 3.2.23 on 2024-01-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_event_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
