# Generated by Django 3.2.23 on 2024-01-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_registration_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='playlist',
            field=models.URLField(blank=True, null=True),
        ),
    ]
