# Generated by Django 3.2.23 on 2024-01-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_registration_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reddit',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mailing_list',
            field=models.BooleanField(default=False, verbose_name='Join our mailing list for info on future events?'),
        ),
    ]
