# Generated by Django 3.2.23 on 2024-01-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_auto_20240118_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations_online',
            field=models.IntegerField(default=0),
        ),
    ]
