# Generated by Django 3.2.23 on 2024-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_event_registrations_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mode',
            field=models.CharField(blank=True, choices=[('In Person', 'In Person'), ('Online', 'Online')], default='In Person', help_text="(If you choose 'In Person' then you can still attend online if you need to.)", max_length=100, null=True, verbose_name='How will you attend?'),
        ),
    ]
