# Generated by Django 3.2.23 on 2024-01-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_auto_20240118_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fully_booked',
            field=models.BooleanField(default=False),
        ),
    ]
