# Generated by Django 3.2.23 on 2024-01-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='link',
            new_name='url',
        ),
    ]
