# Generated by Django 3.2.23 on 2024-02-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_auto_20240131_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ask_for_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Please describe your issue in as much detail as possible. The more we know, the better we can help you.', null=True, verbose_name="What's your issue?"),
        ),
    ]
