# Generated by Django 3.2.23 on 2024-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_auto_20240207_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ask_for_description',
            field=models.BooleanField(default=False),
        ),
    ]
