# Generated by Django 3.2.23 on 2024-02-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_auto_20240207_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
