# Generated by Django 3.2.24 on 2024-02-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_registration_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='email@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='How can we help? Please provide as much detail as possible.'),
        ),
    ]
