# Generated by Django 3.2.24 on 2024-02-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
