# Generated by Django 3.2.24 on 2024-02-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0024_portfolio_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
