# Generated by Django 3.2.24 on 2024-02-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0025_alter_portfolio_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='How can I help? Please provide as much detail as possible.'),
        ),
    ]
