# Generated by Django 3.2.25 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0026_auto_20240215_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mailing',
            field=models.BooleanField(default=False, verbose_name='Receive updates on my work and events?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mailing_list',
            field=models.BooleanField(default=False, verbose_name='Receive emails about future events?'),
        ),
    ]
