# Generated by Django 3.2.25 on 2024-03-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0027_auto_20240314_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tool',
            field=models.BooleanField(default=False),
        ),
    ]
