# Generated by Django 3.2.25 on 2024-03-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0028_portfolio_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
