# Generated by Django 3.2.25 on 2024-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0030_videobackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('image', models.FileField(upload_to='events/')),
                ('location', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
