# Generated by Django 3.2.25 on 2024-06-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0031_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='location',
        ),
    ]
