# Generated by Django 3.2.25 on 2024-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0032_remove_tool_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
