# Generated by Django 3.2.25 on 2024-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0033_alter_tool_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
