# Generated by Django 3.2.25 on 2024-11-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0034_portfolio_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
