# Generated by Django 3.2.25 on 2024-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffsearch', '0002_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='url',
            field=models.URLField(blank=True, default='https://liverpool.ac.uk', null=True),
        ),
    ]
