# Generated by Django 3.2.25 on 2024-03-21 14:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('downloads', models.IntegerField(default=0)),
                ('max_downloads', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='PanoramaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='panorama/')),
                ('downloaded', models.BooleanField(default=False)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panorama.panoramaprofile')),
            ],
        ),
    ]
